package com.nekoplayer.data.api

import com.nekoplayer.lyrics.Lyrics
import com.nekoplayer.lyrics.LrcParser
import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.engine.*
import io.ktor.client.plugins.*
import io.ktor.client.plugins.contentnegotiation.*
import io.ktor.client.plugins.logging.*
import io.ktor.client.request.*
import io.ktor.http.*
import io.ktor.serialization.kotlinx.json.*
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Bilibili字幕API
 * 
 * 提供B站视频字幕获取功能：
 * - 获取视频字幕列表
 * - 下载字幕内容（支持JSON/CC格式）
 * - 转换为LRC格式
 */
class BiliSubtitleApi(engine: HttpClientEngine) {
    
    private val client = HttpClient(engine) {
        install(ContentNegotiation) {
            json(Json {
                ignoreUnknownKeys = true
                isLenient = true
            })
        }
        install(Logging) {
            level = LogLevel.ALL
        }
        install(HttpTimeout) {
            requestTimeoutMillis = 30000
            connectTimeoutMillis = 15000
        }
        defaultRequest {
            header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
            header("Referer", "https://www.bilibili.com")
        }
    }
    
    /**
     * 获取视频字幕列表
     * @param bvid 视频BV号
     * @return 字幕列表（包含语言信息和下载链接）
     */
    suspend fun getSubtitleList(bvid: String): List<BiliSubtitleInfo> {
        return try {
            // 先获取视频信息，包含字幕URL
            val response = client.get("https://api.bilibili.com/x/web-interface/view") {
                parameter("bvid", bvid)
            }
            
            val result = response.body<BiliViewResponse>()
            val subtitleUrl = result.data?.subtitle?.list?.map { subtitle ->
                BiliSubtitleInfo(
                    id = subtitle.id.toString(),
                    language = subtitle.lan,
                    languageName = subtitle.lan_doc,
                    subtitleUrl = subtitle.subtitle_url,
                    isAutoGenerated = subtitle.is_lock == false // 机翻字幕通常is_lock为false
                )
            } ?: emptyList()
            
            subtitleUrl
        } catch (e: Exception) {
            e.printStackTrace()
            emptyList()
        }
    }
    
    /**
     * 获取字幕内容并转换为Lyrics
     * @param subtitleUrl 字幕JSON链接
     * @param title 歌曲标题（用于Lyrics元数据）
     * @param artist 艺术家（用于Lyrics元数据）
     * @return Lyrics对象（如果转换成功）
     */
    suspend fun getSubtitleAsLyrics(
        subtitleUrl: String,
        title: String = "",
        artist: String = ""
    ): Lyrics? {
        return try {
            // B站字幕URL需要添加https:前缀
            val fullUrl = if (subtitleUrl.startsWith("http")) subtitleUrl else "https:$subtitleUrl"
            
            val response = client.get(fullUrl)
            val subtitleData = response.body<BiliSubtitleJson>()
            
            // 转换为LRC格式
            val lrcContent = convertToLrc(subtitleData, title, artist)
            
            // 解析为Lyrics对象
            LrcParser.parse(lrcContent)
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
    
    /**
     * 获取视频的最佳字幕（优先人工字幕，其次机翻）
     * @param bvid 视频BV号
     * @param preferLanguage 优先语言代码（默认zh-CN）
     * @return 字幕信息（如果找到）
     */
    suspend fun getBestSubtitle(
        bvid: String,
        preferLanguage: String = "zh-CN"
    ): BiliSubtitleInfo? {
        val subtitles = getSubtitleList(bvid)
        
        if (subtitles.isEmpty()) return null
        
        // 优先级：人工字幕 > 机翻字幕，优先语言 > 其他语言
        return subtitles
            .sortedWith(compareByDescending<BiliSubtitleInfo> { it.language == preferLanguage }
                .thenByDescending { !it.isAutoGenerated })
            .firstOrNull()
    }
    
    /**
     * 直接获取视频的最佳字幕并转换为Lyrics
     * @param bvid 视频BV号
     * @param title 歌曲标题
     * @param artist 艺术家
     * @return Lyrics对象（如果成功）
     */
    suspend fun fetchLyrics(
        bvid: String,
        title: String = "",
        artist: String = ""
    ): Lyrics? {
        val subtitle = getBestSubtitle(bvid) ?: return null
        return getSubtitleAsLyrics(subtitle.subtitleUrl, title, artist)
    }
    
    /**
     * 将B站字幕JSON转换为LRC格式
     */
    private fun convertToLrc(
        subtitleData: BiliSubtitleJson,
        title: String,
        artist: String
    ): String {
        val sb = StringBuilder()
        
        // 添加元数据
        if (title.isNotBlank()) {
            sb.appendLine("[ti:$title]")
        }
        if (artist.isNotBlank()) {
            sb.appendLine("[ar:$artist]")
        }
        sb.appendLine("[by:Bilibili Subtitle]")
        sb.appendLine()
        
        // 转换字幕条目
        subtitleData.body.forEach { item ->
            val startTime = formatTime(item.from)
            val content = item.content.trim()
            
            if (content.isNotBlank()) {
                sb.appendLine("[$startTime]$content")
            }
        }
        
        return sb.toString()
    }
    
    /**
     * 格式化时间为LRC格式 [mm:ss.xx]
     */
    private fun formatTime(seconds: Double): String {
        val totalMs = (seconds * 1000).toLong()
        val mins = totalMs / 60000
        val secs = (totalMs % 60000) / 1000
        val ms = (totalMs % 1000) / 10  // LRC使用百分之一秒
        
        return String.format("%02d:%02d.%02d", mins, secs, ms)
    }
}

/**
 * 字幕信息
 */
data class BiliSubtitleInfo(
    val id: String,
    val language: String,           // 语言代码，如 "zh-CN"
    val languageName: String,       // 语言名称，如 "中文（中国）"
    val subtitleUrl: String,        // 字幕JSON下载链接
    val isAutoGenerated: Boolean    // 是否为机翻字幕
)

// ==================== API响应数据类 ====================

@Serializable
data class BiliViewResponse(
    val code: Int = 0,
    val message: String = "",
    val data: BiliViewData? = null
)

@Serializable
data class BiliViewData(
    val subtitle: BiliSubtitleData? = null
)

@Serializable
data class BiliSubtitleData(
    val list: List<BiliSubtitleItem> = emptyList()
)

@Serializable
data class BiliSubtitleItem(
    val id: Long = 0,
    val lan: String = "",           // 语言代码
    val lan_doc: String = "",       // 语言名称
    val subtitle_url: String = "",  // 字幕JSON链接
    val is_lock: Boolean = false    // 是否锁定（人工字幕通常为true）
)

/**
 * B站字幕JSON格式
 */
@Serializable
data class BiliSubtitleJson(
    val font_size: Float = 0.4f,
    val font_color: String = "#FFFFFF",
    val background_alpha: Float = 0.5f,
    val background_color: String = "#9C27B0",
    val Stroke: String = "0px",
    val body: List<BiliSubtitleBodyItem> = emptyList()
)

@Serializable
data class BiliSubtitleBodyItem(
    val from: Double = 0.0,         // 开始时间（秒）
    val to: Double = 0.0,           // 结束时间（秒）
    val location: Int = 2,          // 位置（2=底部）
    val content: String = ""        // 字幕内容
)
